spring:
  datasource:
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

  redis:
    host: ${redis.host}
    port: ${redis.port}

  messages:
    basename: i18n/exception
    encoding: UTF-8

logging.level:
  org.hibernate.SQL: debug
# org.hibernate.type: trace

jwt:
  access-length: ${jwt.access.length}
  refresh-token: ${jwt.refresh.token}
  access-key: ${jwt.access.key}
  refresh-key: ${jwt.refresh.key}

springdoc:
  version: v.1.0.0
  packages-to-scan: com.nexters.momo
  swagger-ui:
    path: /swagger-ui
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v1/api-docs
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
