spring:
  datasource:
    url: jdbc:mysql://localhost:3306/momo?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

  redis:
    host: localhost
    port: 6379

  messages:
    basename: i18n/exception
    encoding: UTF-8

logging.level:
  org.hibernate.SQL: debug
# org.hibernate.type: trace

jwt:
  access-length: 1800000 # 30min
  refresh-length: 259200000 # 30day
  access-key:
    testAccessKeytestAccessKeytestAccessKeytestAccessKeytestAccessKeytestAccessKeytestAccessKeytestAccessKeytestAccessKey
  refresh-key:
    testPrivateKeytestPrivateKeytestPrivateKeytestPrivateKeytestPrivateKeytestPrivateKeytestPrivateKeytestPrivateKeytestPrivateKey